### ISSUE TITLE
Can't read local Sentinel-2 JP2 files

### ISSUE THREAD

**Issue by tjordan9** [sentinel-hub/sentinel2-cloud-detector#10]
I'm trying to work through the "sentinel2-cloud-detector-example" (https://github.com/sentinel-hub/sentinel2-cloud-detector/blob/master/examples/sentinel2-cloud-detector-example.ipynb) using Sentinel-2 data previously downloaded to my PC from ESA (https://scihub.copernicus.eu/dhus/#/home).

However, **io_utils.read_jp2()** fails to read any of the Sentinel-2 jp2 files. It looks like all of the bands are 15-bit, and _fix_jp2_image() can fix them. Here is what I tried:

>>> import os
>>> import sentinelhub.io_utils as io_utils
>>> os.listdir('.')
['B01.jp2', 'B02.jp2', 'B03.jp2', 'B04.jp2', 'B05.jp2', 'B06.jp2', 'B07.jp2', 'B08.jp2', 'B09.jp2', 'B10.jp2', 'B11.jp2', 'B12.jp2', 'B8A.jp2', 'metadata.xml', 'preview.jpg', 'TCI.jp2']

>>> io_utils.read_jp2_image('./B01.jp2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\apps\Anaconda3\lib\site-packages\sentinelhub\io_utils.py", line 87, in read_jp2_image
    return _fix_jp2_image(image, bit_depth)
  File "C:\apps\Anaconda3\lib\site-packages\sentinelhub\io_utils.py", line 359, in _fix_jp2_image
    return image >> 1
TypeError: unsupported operand type(s) for >>: 'Jpeg2KImageFile' and 'int'

B03 and other jp2 files also fail the same way:
>>> io_utils.read_jp2_image('./B03.jp2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\apps\Anaconda3\lib\site-packages\sentinelhub\io_utils.py", line 87, in read_jp2_image
    return _fix_jp2_image(image, bit_depth)
  File "C:\apps\Anaconda3\lib\site-packages\sentinelhub\io_utils.py", line 359, in _fix_jp2_image
    return image >> 1
TypeError: unsupported operand type(s) for >>: 'Jpeg2KImageFile' and 'int'

**How can I read the local jp2 files so I can use the S2PixelCloudDetector?** 
    cloud_detector = S2PixelCloudDetector(threshold=0.4, average_over=4, dilation_size=2)
    local_bands = ???
    cloud_masks = cloud_detector.get_cloud_masks(local_bands)

Thanks for any help you can provide.

**Comment by AleksMat** [comment]
Hi @tjordan9,

this problem is actually caused by incorrectly installed `Pillow` Python package which is used for reading Jpeg 2000 images. This usually happens on Windows if OpenJpeg system library is missing or `Pillow` doesn't find it. The solution is to reinstall `Pillow` and instead of normal installation install it from a wheel. The wheel will have OpenJpeg library included. For example [this site](https://www.lfd.uci.edu/~gohlke/pythonlibs/) contains wheels for most commonly used Python packages .

By the way, we have now released `sentinelhub` package version `2.4.2` which raises a more informative error when this happens. Thus letting the user know to reinstall `Pillow` from a wheel.
