### ISSUE TITLE
Cannot find the plotting_utils library

### ISSUE THREAD

**Issue by Pompey21** [sentinel-hub/sentinel2-cloud-detector#34]
First of all I would like to congratulate you on this project - quite remarkable! 

I accessed the pictures another way (not with sentinelhub) and have transformed them into the numpy arrays, is that also the format in which your bands are used by the cloud-masking methods?

**Comment by AleksMat** [comment]
Hi @Pompey21,

It's great to see you like the project.

- The input bands have to be in a numpy array object which you can see from the [docstrings](https://github.com/sentinel-hub/sentinel2-cloud-detector/blob/v1.5.0/s2cloudless/cloud_detector.py#L121). You might also find useful to check some past issues, such as https://github.com/sentinel-hub/sentinel2-cloud-detector/issues/1, where users used s2cloudless without Sentinel Hub and posted some code about it. It can be a bit tricky because you have to make sure that:
  * jp2 files get correctly decoded into numpy arrays,
  * you resample bands to the same resolution,
  * convert digital numbers into reflectance values (dividing by 10000),
  * order the bands into the [correct order](https://github.com/sentinel-hub/sentinel2-cloud-detector/blob/v1.5.0/s2cloudless/utils.py#L6).

- `plotting_utils` is not a library, it is just [this module](https://github.com/sentinel-hub/sentinel2-cloud-detector/blob/v1.5.0/examples/plotting_utils.py). Importing it into the notebook should work if you keep them both in the same folder. If not, you can always just copy-paste the code from the module into the notebook.

**Comment by Pompey21** [comment]
Hey @AleksMat, thanks a lot for the fast response. Yes, I just realised ... silly me, I completely missed that .py file! 
Sweet, thank you very much, I shall check it out!
