### ISSUE TITLE
[HELP] Sentinel-2 L2A Cirrus Band

### ISSUE THREAD

**Issue by mthsdiniz** [sentinel-hub/sentinel2-cloud-detector#79]
According to this [document by Sentinel-hub](https://docs.sentinel-hub.com/api/latest/data/sentinel-2-l2a/) the cirrus band B10 was excluded as it does not contain any "bottom of the atmosphere" information. 

Is there a way to use the s2cloudless cloud detector without that band? If yes, how so?

Note: I'm trying to apply the package to a regular sentinel-l2a not acquired through sentinel-2 hub, therefore i dont have access to classification bands. Besides the regular bands, i have access to AOT (Aerosol Optical Thickness), WVP (Water Vapour) and SCL.

Thanks!

**Comment by mlubej** [comment]
Hi @mthsdiniz 

Unfortunately, the s2cloudless is meant only for L1C, so it won't work on L2A. There are a few workarounds:
- get access somehow (Sentinel Hub, etc.. ) to L1C data for the same area, run the s2cloudless on that, and copy the classification over
- do a request to Sentinel Hub with the same bounding box and timestamps for downloading pre-calculated CLP and CLM features for cloud probabilities and masks, respectively

The second option is cheaper, since you don't need to download so many things, but the pre-computed CLP/CLM were run on 160m resolution.

**Comment by mlubej** [comment]
No reply, closing.
